Document: smallstep-auto-renew
Title: Debian smallstep-auto-renew Manual
Author: <insert document author here>
Abstract: This manual describes what smallstep-auto-renew is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/smallstep-auto-renew/smallstep-auto-renew.sgml.gz

Format: postscript
Files: /usr/share/doc/smallstep-auto-renew/smallstep-auto-renew.ps.gz

Format: text
Files: /usr/share/doc/smallstep-auto-renew/smallstep-auto-renew.text.gz

Format: HTML
Index: /usr/share/doc/smallstep-auto-renew/html/index.html
Files: /usr/share/doc/smallstep-auto-renew/html/*.html
